const worldFrequency = 10000; // update every N milliseconds

const twitch = {
    channel: 'erodozer',
    levelUpReward: '1761edbb-e99d-4162-8da1-602e62e1b06c',
    changeJobReward: 'af61d9a9-b88a-4f38-8fd2-5d3631507f32',
    boostReward: 'db0b9496-b1bd-41eb-9ee0-2e0a07da299b',
};

const ailments = [
    {
        id: "hungry",
        name: "😩",
        priority: 1.0,
        inhibit: {
            money: 0.25,
            food: 0.0,
            culture: 0.25,
        },
        afflicted(member) {
            return (member.health / (member.currentJob.maxHealth || 100)) < 0.5;
        }
    },
    {
        id: "excited",
        name: "🥳",
        priority: 10.0,
        inhibit: {
            money: 2.0,
            food: 2.0,
            culture: 2.0,
        },
        afflicted(member) {
            return member.ailments.excited > 0;
        }
    },
    {
        id: "sick",
        name: "🤢",
        priority: 100.0,
        inhibit: {
            money: 0.0,
            food: 0.0,
            culture: 0.0,
        },
        afflicted(member) {
            return member.ailments.sick > 0;
        }
    }
];

const jobs = [
    {
        id: "laborer",
        name: "🔨",
        color: "#666666",
        stats: {
            money: 4.0,
        },
        consume: {
            food:{
                frequency: 1.0,
                amount: 1.0,
            }
        }
    },
    {
        id: "hunter",
        name: "🏹",
        color: "#8fbc8f",
        stats: {
            money: 1.0,
            food: 3.0,
        },
        consume: {
            food:{
                frequency: 1.0,
                amount: 1.0,
            }
        },
        inhibitor: {
            hungry: {
                food: 0.5,
            },
        }
    },
    {
        id: "scholar",
        name: "📕",
        color: "#ffe28a",
        stats: {
            culture: 4.0,
        },
        consume: {
            food:{
                frequency: 1.0,
                amount: 2.0,
            }
        }
    },
    {
        id: "chef",
        name: "🍴",
        color: "#eea990",
        stats: {
            food: 2.0,
            culture: 2.0,
        },
        consume: {
            food:{
                frequency: 1.0,
                amount: 1.0,
            }
        }
    },
    {
        id: "artist",
        name: "🎨",
        color: "#962fbf",
        stats: {
            money: 2.0,
            culture: 2.0,
        },
        consume: {
            food:{
                frequency: 3.0,
                amount: 1.0,
            }
        }
    },
    {
        id: "warrior",
        name: "⚔️",
        color: "#dc143c",
        stats: {
            money: 2.0,
        },
        consume: {
            food:{
                frequency: 1.0,
                amount: 5.0,
            }
        }
    },
    {
        id: "doctor",
        name: "💊",
        color: "#fff4e6",
        stats: {
            money: 2.0,
        },
        consume: {
            food:{
                frequency: 1.0,
                amount: 1.0,
            },
        }
    },
    {
        id: "farmer",
        name: "🌽",
        color: "#c98143",
        stats: {
            food: 4.0,
        },
        consume: {
            food: {
                frequency: 1.0,
                amount: 1.0,
            }
        },
        inhibitor: {
            hungry: {
                food: 0.8,
            }
        }
    }
]

const enemies = {
    // From https://gamefaqs.gamespot.com/boards/945236-disgaea-ds/45791754
    names: [
        "Abigor",
        "Ace",
        "Achilles",
        "Acid",
        "Adieu",
        "Adrian",
        "Aegis",
        "Agaliarept",
        "Agares",
        "Agora",
        "Agrippa",
        "Ahya",
        "Aisha",
        "Ajikage",
        "Akey",
        "Akiblo",
        "Akira",
        "Al",
        "Alan",
        "Albert",
        "Aldis",
        "Alex",
        "Alexander",
        "Alfred",
        "Algoreo",
        "Alice",
        "Allen",
        "Alllietta",
        "Allocen",
        "Alpha",
        "Alquen",
        "Alsace",
        "Alto",
        "Alucard",
        "Alumina",
        "Amdusias",
        "Amia",
        "Amnelis",
        "Amon",
        "Amulet",
        "Amy",
        "Anabell",
        "Anastasia",
        "Andras",
        "Andre",
        "Andrealphus",
        "Andrew",
        "Andromalius",
        "Angeline",
        "Animus",
        "Anita",
        "Anna",
        "Annerose",
        "Annis",
        "Ansbach",
        "Antaios",
        "Antonio",
        "Aphrodite",
        "Apollo",
        "Appleton",
        "Aqua",
        "Aragorn",
        "Arbaux",
        "Archie",
        "Aria",
        "Arias",
        "Ariel",
        "Arina",
        "Arion",
        "Ark",
        "Armaros",
        "Artemis",
        "Arthur",
        "Asbestos",
        "Ash",
        "Astarte",
        "Athena",
        "Athetosis",
        "Athos",
        "August",
        "Aura",
        "Aurelia",
        "Auslese",
        "Avan",
        "Axis",
        "Azazel",
        "Baggins",
        "Baghi",
        "Bakala",
        "Balalaika",
        "Baldr",
        "Baldwin",
        "Balin",
        "Ballad",
        "Baltis",
        "Barak",
        "Barbara",
        "Barsom",
        "Beatrice",
        "Beauchette",
        "Beaufort",
        "Becky",
        "Belinus",
        "Bellatrix",
        "Belle",
        "Belphegor",
        "Benten",
        "Beowulf",
        "Bereth",
        "Bertrand",
        "Betty",
        "Bianca",
        "Bifrons",
        "Billy",
        "Birru",
        "Bismarck",
        "Blair",
        "Bob",
        "Bonaparte",
        "Bonita",
        "Boo",
        "Boss",
        "Bossanova",
        "Bouquet",
        "Bravo",
        "Brenda",
        "Brigit",
        "Brocken",
        "Bruce",
        "Buelle",
        "Byung",
        "Cadmus",
        "Cagliostro",
        "Cameo",
        "Cameron",
        "Canard",
        "Caradoc",
        "Carbide",
        "Carl",
        "Carlos",
        "Carlton",
        "Carmalide",
        "Carol",
        "Carrie",
        "Cathy",
        "Caulang",
        "Cecil",
        "Cecila",
        "Celcia",
        "Chapeau",
        "Charles",
        "Charlotte",
        "Charmant",
        "Chen",
        "Chiangley",
        "Chicori",
        "Chlordane",
        "Choux",
        "Christine",
        "Christoph",
        "Chuck",
        "Ciel",
        "Cinderella",
        "Cinzano",
        "Clarion",
        "Claris",
        "Clefford",
        "Clipton",
        "Clive",
        "Cloak",
        "Clove",
        "Clown",
        "Clutch",
        "Codeine",
        "Cognac",
        "Comet",
        "Connie",
        "Coral",
        "Cornerius",
        "Cornet",
        "Coronet",
        "Corriedale",
        "Corsage",
        "Cotton",
        "Couturiere",
        "Crescentia",
        "Croissant",
        "Crouton",
        "Cymbal",
        "Cynthia",
        "Damian",
        "Dan",
        "Dandelion",
        "Dandy",
        "Daphne",
        "Darby",
        "Debonair",
        "Delia",
        "Delta",
        "Devon",
        "Diana",
        "Dietrich",
        "Dilan",
        "Djinn",
        "Dog",
        "Dogma",
        "Dolce",
        "Domitus",
        "Don Juan",
        "Donnie",
        "Dora",
        "Dorro",
        "Douglas",
        "Drew",
        "Dschingis",
        "Duke",
        "Dustin",
        "Dynamo",
        "Ebonite",
        "Eclair",
        "Ecole",
        "Ed",
        "Edgar",
        "Eida",
        "Eigendorf",
        "Eiji",
        "Eisbein",
        "Eisenach",
        "Eisenerz",
        "Elaine",
        "Eleanor",
        "Elena",
        "Elfir",
        "Elfriede",
        "Eligor",
        "Elisa",
        "Elise",
        "Elizabeth",
        "Elphin",
        "Elsa",
        "Elsheimer",
        "Ema",
        "Emilio",
        "Emmy",
        "Empress",
        "Engarde",
        "Enigma",
        "Epsilon",
        "Erg",
        "Erica",
        "Ernst",
        "Escargo",
        "Esmerelda",
        "Esparanto",
        "Esprit",
        "Estel",
        "Ethel",
        "Ethos",
        "Etranger",
        "Etwas",
        "Eve",
        "Exocet",
        "Fabrizia",
        "Faith",
        "Falco",
        "Falfie",
        "Falquenne",
        "Falus",
        "Fatima",
        "Faustina",
        "Fay",
        "Fei-Hung",
        "Felicia",
        "Fenella",
        "Ferne",
        "Ferri",
        "Fiador",
        "Fiona",
        "Fixer",
        "Flauros",
        "Flea",
        "Fleur",
        "Flora",
        "Florence",
        "Fondue",
        "Foon",
        "Francine",
        "Frank",
        "Freda",
        "Frederica",
        "Freya",
        "Friedrich",
        "Fubuki",
        "Fuke",
        "Fyz",
        "Gabbot",
        "Gainer",
        "Gair",
        "Gairu",
        "Galaxy",
        "Gallant",
        "Gambit",
        "Gandalf",
        "Gansel",
        "Garcon",
        "Gareth",
        "Garnet",
        "Garon",
        "Garosh",
        "Gash",
        "Gaston",
        "Gaufres",
        "Gawein",
        "Gaws",
        "Gazette",
        "Geese",
        "Geist",
        "Gemeiner",
        "General",
        "George",
        "Geraint",
        "Gerhard",
        "Geronimo",
        "Gesellschaft",
        "Gestalt",
        "Gewalt",
        "Giko",
        "Gillian",
        "Gimlet",
        "Gin",
        "Ginger",
        "Gingham",
        "Gloria",
        "Gnocchi",
        "Goblet",
        "Goemon",
        "Goldie",
        "Grace",
        "Grammy",
        "Gray",
        "Great",
        "Gremory",
        "Griffon",
        "Grune",
        "Guenever",
        "Gustav",
        "Guy",
        "Haken",
        "Halver",
        "Hannah",
        "Hanzo",
        "Harlequin",
        "Harrison",
        "Harry",
        "Hartwin",
        "Haydn",
        "Hazuki",
        "Hector",
        "Hedwig",
        "Heinrich",
        "Heinz",
        "Helen",
        "Hellicios",
        "Hermina",
        "Hickory",
        "Hilde",
        "Homeros",
        "Horchata",
        "Hrothgar",
        "Hulloc",
        "Hun",
        "Husky",
        "Idea",
        "Idola",
        "Ilumina",
        "Ingrid",
        "Ipos",
        "Ippril",
        "Iris",
        "Irma",
        "Isabel",
        "Ishtar",
        "Isolde",
        "Ivan",
        "Jaccard",
        "Jack",
        "Jackal",
        "Jam",
        "James",
        "Jane",
        "Jarble",
        "Jasmine",
        "Jeanne",
        "Jessica",
        "Jesus",
        "Jet",
        "Jeyal",
        "Jill",
        "Jim",
        "Joanna",
        "Joclyn",
        "Joe",
        "Johann",
        "Johanson",
        "John",
        "Johnson",
        "Joker",
        "Jordan",
        "Jruu",
        "Jubei",
        "Judas",
        "Judith",
        "Julie",
        "Julienne",
        "Julietta",
        "Julius",
        "Justice",
        "Kain",
        "Kaiser",
        "Kanna",
        "Karen",
        "Karin",
        "Karla",
        "Karrey",
        "Kary",
        "Kasekuchen",
        "Kasuba",
        "Kasumi",
        "Kate",
        "Katerine",
        "Katrina",
        "Keeseling",
        "Keim",
        "Keith",
        "Kennel",
        "Kessler",
        "Khmer",
        "Kinkan",
        "Kit",
        "Kiwi",
        "Klara",
        "Klimina",
        "Klomn",
        "Kocher",
        "Komugi",
        "Konga",
        "Konga",
        "Kosmos",
        "Krajicek",
        "Kriemhild",
        "Kurt",
        "Kyle",
        "Kyrielich",
        "Lachesis",
        "Laelia",
        "Lafeene",
        "Lambda",
        "Lana",
        "Lancelot",
        "Lancia",
        "Lao",
        "Lapiz",
        "Larugo",
        "Laslo",
        "Laudigan",
        "Launceor",
        "Laura",
        "Lauren",
        "Laverna",
        "Leia",
        "Leighton",
        "Lemon",
        "Lena",
        "Lenn",
        "Leon",
        "Leticia",
        "Liberty",
        "Liese",
        "Ligia",
        "Lily",
        "Limbo",
        "Lime",
        "Linda",
        "Linker",
        "Lionel",
        "Lisa",
        "Lita",
        "Logan",
        "Lone Wolf",
        "Lorelei",
        "Love",
        "Lowell",
        "Lucille",
        "Lucretia",
        "Ludwig",
        "Luke",
        "Luna",
        "Lundi",
        "Lunista",
        "Luphina",
        "Lutius",
        "Lynn",
        "Macky",
        "Madonna",
        "Magdalena",
        "Magenta",
        "Maggie",
        "Maggiore",
        "Magnolia",
        "Magnus",
        "Malcolm",
        "Malthus",
        "Mao",
        "Marchocias",
        "Marco",
        "Margarita",
        "Mariah",
        "Mariell",
        "Marin",
        "Marissa",
        "Marius",
        "Mark",
        "Marl",
        "Marlone",
        "Mars",
        "Martin",
        "Mary",
        "Matilda",
        "Matthias",
        "Maximillian",
        "Maximus",
        "May",
        "Maya",
        "Mayden",
        "Mazurka",
        "Medea",
        "Meena",
        "Megan",
        "Meimu",
        "Meindorf",
        "Melchior",
        "Melissa",
        "Melody",
        "Memory",
        "Menuette",
        "Mephisto",
        "Mercia",
        "Merium",
        "Merle",
        "Meryl",
        "Metiee",
        "Meyer",
        "Michelle",
        "Mihail",
        "Mike",
        "Milan",
        "Millia",
        "Minerva",
        "Ming-Sia",
        "Mint",
        "Mirage",
        "Misha",
        "Mocchus",
        "Mocci",
        "Modero",
        "Mohawk",
        "Moira",
        "Moloch",
        "Monar",
        "Mordred",
        "Morpheus",
        "Mort",
        "Mourvin",
        "Muireann",
        "Musashi",
        "Mustafa",
        "Muzari",
        "Myrddin",
        "Nadia",
        "Napoleon",
        "Natalie",
        "Nebula",
        "Neidhardt",
        "Neige",
        "Neirin",
        "Nel",
        "Nero",
        "Nessler",
        "Nicholas",
        "Nirva",
        "Nitro",
        "Noelle",
        "Noin",
        "Noir",
        "Non",
        "Nyah",
        "Oath",
        "Oce",
        "Octavia",
        "Odessia",
        "Oidepus",
        "Olga",
        "Olias",
        "Olive",
        "Olivier",
        "Olympia",
        "Omega",
        "Oracle",
        "Orivea",
        "Orson",
        "Oscar",
        "Otto",
        "Ouzo",
        "Ozmyere",
        "Palmiro",
        "Pamela",
        "Pamille",
        "Pancho",
        "Pastel",
        "Patrick",
        "Paulman",
        "Peetan",
        "Penelope",
        "Percival",
        "Perfume",
        "Perrin",
        "Peter",
        "Petite",
        "Phobos",
        "Phoenix",
        "Phyllis",
        "Pia",
        "Pierina",
        "Pizzicato",
        "Pock",
        "Poette",
        "Polly",
        "Pollyanna",
        "Pratima",
        "Praxis",
        "Primula",
        "Pris",
        "Pritny",
        "Pucelle",
        "Quess",
        "Quilt",
        "Quinine",
        "Qwerty",
        "Rachel",
        "Raelene",
        "Ralph",
        "Ran",
        "Rana",
        "Rangue",
        "Rastel",
        "Ray",
        "Rayrord",
        "Razz",
        "Reckendorf",
        "Red",
        "Rem",
        "Remiel",
        "Remy",
        "Rena",
        "Rhea",
        "Rhett",
        "Riali",
        "Ribbon",
        "Ricardo",
        "Rich",
        "Richard",
        "Ripley",
        "Robert",
        "Robinson",
        "Robyn",
        "Rocielle",
        "Rockwell",
        "Roderick",
        "Roger",
        "Rolan",
        "Romeo",
        "Ronica",
        "Rose",
        "Rosetta",
        "Rosewood",
        "Rouge",
        "Roxanne",
        "Rubashka",
        "Ruger",
        "Russell",
        "Ryan",
        "Sabrina",
        "Sabrosa",
        "Sakura",
        "Saladin",
        "Salmun",
        "Salsburg",
        "Salvia",
        "Samchay",
        "Samson",
        "Samuel",
        "Sarafan",
        "Sarah",
        "Saratoga",
        "Saria",
        "Sarome",
        "Sasha",
        "Sasuke",
        "Savarin",
        "Scarlet",
        "Scherzo",
        "Schia",
        "Scotch",
        "Sebastian",
        "Sector",
        "Seila",
        "Seimei",
        "Seito",
        "Selene",
        "Sepia",
        "Shade",
        "Shadow",
        "Shamrock",
        "Sharon",
        "Shelby",
        "Sherbert",
        "Sherry",
        "Shidoshi",
        "Shredder",
        "Si",
        "Sialon",
        "Sibyl",
        "Sigma",
        "Sigurd",
        "Sigurd",
        "Silica",
        "Silver",
        "Silvia",
        "Siniud",
        "Siren",
        "Sirius",
        "Skald",
        "Skinner",
        "Sludge",
        "Snob",
        "Solaris",
        "Soleil",
        "Solis",
        "Soliton",
        "Sombart",
        "Sonata",
        "Sonette",
        "Sonic",
        "Sonic",
        "Sophia",
        "Souffle",
        "Spade",
        "Spartan",
        "Spiral",
        "Staden",
        "Star",
        "Steilhang",
        "Stigma",
        "Stinger",
        "Stout",
        "Strawberry",
        "Sunday",
        "Sushi",
        "Suzanna",
        "Suzie",
        "Suzu",
        "Svana",
        "Sweet",
        "Tamarin",
        "Tamia",
        "Tamiel",
        "Tandoori",
        "Tanpopo",
        "Tanya",
        "Tao",
        "Tarte",
        "Teresa",
        "Terrine",
        "Tesse",
        "Theo",
        "Theta",
        "Thomas",
        "Tiffany",
        "Tigre",
        "Tina",
        "Tinker",
        "Titan",
        "Torquay",
        "Tranza",
        "Trianna",
        "Trinity",
        "Tristan",
        "Tristram",
        "Turbo",
        "Ulrich",
        "Undine",
        "Uranus",
        "Uriel",
        "Va",
        "Valencia",
        "Valerius",
        "Valgus",
        "Vanessa",
        "Vanessa",
        "Vasquez",
        "Vediva",
        "Vega",
        "Venus",
        "Vera",
        "Veritace",
        "Verne",
        "Verrier",
        "Vicky",
        "Victoria",
        "Vilma",
        "Vine",
        "Violette",
        "Vladimir",
        "Vodka",
        "Volac",
        "Waffle",
        "Walter",
        "Warren",
        "Wasabi",
        "Wendy",
        "Werner",
        "Wesker",
        "Wilhelm",
        "Willaby",
        "William",
        "Willock",
        "Windy",
        "Wing",
        "Winney",
        "Wolf",
        "X-14D3",
        "Xabia",
        "Xandria",
        "Xe",
        "Xenon",
        "Xig",
        "Yanyan",
        "Ygerne",
        "York",
        "Yuki",
        "Yvette",
        "Yvonne",
        "Yvonne",
        "Z",
        "Zanac",
        "Zebra",
        "Zeeman",
        "Zeke",
        "Zenia",
        "Zeolite",
        "Zero",
        "Zeus",
        "Zeveck",
        "Zisakuzien",
        "Ziska",
        "Zodiac"
    ],
    types: [
        {
            id: "bandit",
            nameFormat: (name) => `🥷 Bandit ${name}`,
            maxHealth: 10,
            unitWeight: 2,
            plunder: {
                money: 3.0,
                food: 3.0,
                culture: 5.0,
            },
        },
        {
            id: "wolf",
            nameFormat: (name) => `🐺 ${name}woof`,
            maxHealth: 5,
            unitWeight: 1,
            plunder: {
                food: 5.0,
            },
        },
        {
            id: "dragon",
            nameFormat: (name) => `🐲 ${name} the Dragon`,
            maxHealth: 100,
            unitWeight: 5,
            plunder: {
                money: 10.0,
                food: 3.0,
            }
        }
    ]
}

window.config = {
    worldFrequency,
    twitch,
    ailments,
    jobs,
    enemies,
};
